/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CiRNX2VAf",
    "aws_user_pools_web_client_id": "51vf7847fk3bureds388i49sf0",
    "oauth": {}
};


export default awsmobile;
